### PR TITLE
Hover to focus functionality

### PR DESCRIPTION
**Pull request by AlasEyrd**
maybe a bug with right click menus? will evaluate.

### CODE REVIEW

**Comment by vardy** [comment]
Thanks for taking the time to do this.
I feel the change does not fit the spirit of the app though, and the ability to move windows without focusing is actually a good thing in my opinion. Feel free to let me know your thoughts, I'll close this PR later.
Cheers.

**Comment by AlasEyrd** [comment]
I don't know what you mean. This doesn't change window moving functionality, it just makes focusing on other windows a lot easier. In upstream aphelia, I can't focus on windows without using the move keybind.

**Comment by AlasEyrd** [comment]
I'll write this into a dwm-style patch for myself and others, if you don't want to merge it. Just makes my life an order of magnitude easier.

**Comment by vardy** [comment]
> I don't know what you mean. This doesn't change window moving functionality, it just makes focusing on other windows a lot easier. In upstream aphelia, I can't focus on windows without using the move keybind.

Oh! Apologies, I must have miss-understood the intention. Odd that you're having issues with focusing windows...

Merging the PR, thanks.

**Pull request merged**
